### ISSUE TITLE
Shell speudocode

### ISSUE THREAD

**Issue by clingaid** [JonathanGrant92/CS2050-001_Project06#5]
Pseudo code for shell short
List
Space = length (list) / 2
While (space > 0 ) {
For ( i = 0, i + space < length, i++) {
If ( list [i] > list [i + space] }
Swap list [i] and list[i+ space] {
Space = space -1

**Comment by JonathanGrant92** [comment]
Don't create a duplicate issue. Post the contribution in a relevant existing file, create a new one, or comment the relevant existing issue. Also, the "pseudo-code" that our professor wants should be complete sentences with no code syntax. Try completing the shell sort method in the .java file, and make a commit.

IE 

If ( list [i] > list [i + space] }
Swap list [i] and list[i+ space] {
Space = space -1

Becomes:

If the current value is greater than the next spaced value, then swap the indices of these values in the list and decrement space.

Pseudocode doesn't have to make logical sense, but these should be descriptive sentences. Sometimes, code doesn't make sense, but we can always revise as needed. If you have questions about translating code to sentences, or the method's implementation, please post on discord/slack and I will get back to you. Also, the LAs are on Discord too.
